/*
  Script de inicializacao do banco local do projeto.

  Conexao esperada pelo backend:
    server: localhost
    port: 1433
    database: AUTOMACAO-PLANILHAS
    user: sa

  Usuario administrador inicial:
    login: admin
    senha: admin123
*/

IF DB_ID(N'AUTOMACAO-PLANILHAS') IS NULL
BEGIN
    CREATE DATABASE [AUTOMACAO-PLANILHAS];
END;
GO

USE [AUTOMACAO-PLANILHAS];
GO

IF OBJECT_ID(N'dbo.US_USUARIOS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.US_USUARIOS (
        US_CODIGO INT IDENTITY(1,1) NOT NULL,
        US_NOME VARCHAR(100) NOT NULL,
        US_LOGIN VARCHAR(14) NOT NULL,
        US_SENHA VARCHAR(500) NOT NULL,
        US_PERMISSAO CHAR(1) NOT NULL,
        US_CRIADO_EM DATETIME2(0) NOT NULL
            CONSTRAINT DF_US_USUARIOS_CRIADO_EM DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_US_USUARIOS PRIMARY KEY CLUSTERED (US_CODIGO),
        CONSTRAINT UQ_US_USUARIOS_LOGIN UNIQUE (US_LOGIN),
        CONSTRAINT CK_US_USUARIOS_PERMISSAO CHECK (US_PERMISSAO IN ('A', 'P'))
    );
END;
GO

IF OBJECT_ID(N'dbo.HS_HISTORICO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HS_HISTORICO (
        HS_CODIGO INT IDENTITY(1,1) NOT NULL,
        HS_USCODIGO INT NOT NULL,
        HS_ACAO VARCHAR(255) NOT NULL,
        HS_CRIADO_EM DATETIME2(0) NOT NULL
            CONSTRAINT DF_HS_HISTORICO_CRIADO_EM DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_HS_HISTORICO PRIMARY KEY CLUSTERED (HS_CODIGO),
        CONSTRAINT FK_HS_HISTORICO_US_USUARIOS FOREIGN KEY (HS_USCODIGO)
            REFERENCES dbo.US_USUARIOS (US_CODIGO)
    );
END;
GO

IF OBJECT_ID(N'dbo.HP_HISTORICO_PLANILHAS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HP_HISTORICO_PLANILHAS (
        HP_CODIGO INT IDENTITY(1,1) NOT NULL,
        HP_USCODIGO INT NOT NULL,
        HP_NOMEPLANILHA VARCHAR(255) NOT NULL,
        HP_LOCALPLANILHA VARCHAR(100) NULL,
        HP_STATUS VARCHAR(100) NOT NULL,
        HP_ERROR VARCHAR(500) NULL,
        HP_CRIADO_EM DATETIME2(0) NOT NULL
            CONSTRAINT DF_HP_HISTORICO_PLANILHAS_CRIADO_EM DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_HP_HISTORICO_PLANILHAS PRIMARY KEY CLUSTERED (HP_CODIGO),
        CONSTRAINT FK_HP_HISTORICO_PLANILHAS_US_USUARIOS FOREIGN KEY (HP_USCODIGO)
            REFERENCES dbo.US_USUARIOS (US_CODIGO)
    );
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM dbo.US_USUARIOS
    WHERE US_LOGIN = 'admin'
)
BEGIN
    INSERT INTO dbo.US_USUARIOS (
        US_NOME,
        US_LOGIN,
        US_SENHA,
        US_PERMISSAO
    )
    VALUES (
        'Administrador',
        'admin',
        'admin123',
        'A'
    );
END;
GO
